### ISSUE TITLE
1.9.4 version on server with forge 1.10 immediately upon entering world from client crash

### ISSUE THREAD

**Issue by JohnRohner** [SleepyTrousers/EnderZoo#140]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 6/25/16 12:09 AM
Description: Exception ticking world

java.lang.NoSuchMethodError: crazypants.enderzoo.entity.EntityFallenKnight.func_82201_a(I)V
	at crazypants.enderzoo.entity.EntityFallenKnight.func_180482_a(EntityFallenKnight.java:279)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:154)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at crazypants.enderzoo.entity.EntityFallenKnight.func_180482_a(EntityFallenKnight.java:279)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:154)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['a'/357, l='world', x=-116.66, y=185.00, z=-110.40]]
	Chunk stats: ServerChunkCache: 563 Drop: 0
	Level seed: 5574457897082764526
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 36615036 game time, 12886748 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 44585 (now: false), thunder time: 14290 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 615285696 bytes (586 MB) / 963117056 bytes (918 MB) up to 963117056 bytes (918 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.0.1986 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10-12.18.0.1986-1.10.0-universal.jar) 
	UCHIJAAAA	Forge{12.18.0.1986} [Minecraft Forge] (forge-1.10-12.18.0.1986-1.10.0-universal.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2026} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2026-universal.jar) 
	UCHIJAAAA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
	UCHIJAAAA	BTFU{1} [BTFU] (BTFU-1.9.4-1.5.jar) 
	UCHIJAAAA	creativecore{1.4.0} [CreativeCore] (CreativeCore v1.4 mc1.9.4.jar) 
	UCHIJAAAA	Dynmap{2.3-3} [Dynmap] (Dynmap-2.3-forge-1.9.4.jar) 
	UCHIJAAAA	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UCHIJAAAA	gravestone{1.4.1} [Gravestone] (Gravestone Mod 1.4.1.jar) 
	UCHIJAAAA	InfernalMobs{1.7.0} [Infernal Mobs] (InfernalMobs-1.9.4.jar) 
	UCHIJAAAA	AS_Ruins{16.1} [Ruins Spawning System] (Ruins-1.9.4.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 5; [EntityPlayerMP['a'/357, l='world', x=-116.66, y=185.00, z=-110.40]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AnrDaemon** [comment]
And just who told you that running 1.9.4 mods on 1.10 would be a smooth and bug-free experience?

**Comment by Drullkus** [comment]
A marketing team.

**Comment by tterrag1098** [comment]
To be fair, most mods do. However, EnderZoo will require an actual update.

**Comment by Morpheus1101** [comment]
Bloodmoon has issues in 1.10 as well just fyi to poster

**Comment by JohnRohner** [comment]
LOL, Forge says 1.9.4 is good with 1.10:
Build 1.10-12.18.0.1983-1.10.0:
	cpw:
		Accept more 1.9.4 version strings. Fix NPE for custom villager types and
		their associated zombie spawns. Still needs review.

**Comment by JohnRohner** [comment]
Build 1.9.4-12.17.0.1978-1.10.0:
	cpw:
		In accordance with our stated goal of relicensing Forge to LGPL v2.1,
		this commit enacts that change. Although it is using the 1.9.4 codebase,
		it is intended that this branch become public with the 1.10 changes, as
		such the license will take effect at that time. The three commits from
		persons who have failed to accept the new license, as documented in
		#2789, have had their commits reverted. This should complete the license
		transition. Commits after the commit date of this commit should be
		considered licensed by LGPLv2.1, as indicated in LICENSE-new.txt. All
		patches are now considered owned by the Forge project and Forge
		Development LLC in particular (note that they will not get the license
		boilerplate, as they are machine generated files).

**Comment by HenryLoenwind** [comment]
If you're unhappy that a mod for 1.9.4 doesn't work on 1.10, take it up with Forge.

A 1.10 version of EnderZoo will come in time.
