### ISSUE TITLE
Errors in the background

### ISSUE THREAD

**Issue by LordMortus** [SleepyTrousers/EnderZoo#178]
While tabbing out of my game I noticed this in the output window:

**Comment by HenryLoenwind** [comment]
( https://github.com/SleepyTrousers/EnderZoo/blob/master/src/main/java/crazypants/enderzoo/entity/EntityFallenMount.java#L42 needs init)

**Comment by Ricket** [comment]
I saw the same in my server console tonight.

```
[20:12:20] [Server thread/ERROR] [FML]: An Entity type crazypants.enderzoo.entity.EntityFallenMount has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1728) ~[sn.class:?]
        at net.minecraft.entity.Entity.func_70039_c(Entity.java:1610) ~[sn.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:371) [avd.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:184) [avd.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:203) [lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:231) [lv.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1015) [lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:647) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at crazypants.enderzoo.entity.EntityFallenMount.func_70014_b(EntityFallenMount.java:226) ~[EntityFallenMount.class:?]
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1699) ~[sn.class:?]
        ... 10 more
```

All The Mods 2 v0.68

EnderZoo-1.11.2-1.3.0.46
