### ISSUE TITLE
Server Crash - Grinder kills horse

### ISSUE THREAD

**Issue by SirWilli** [SleepyTrousers/EnderZoo#31]
hey,
the server crashes if a mfr grinder kills a horse from enderzoo
```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:906)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1746)
	at net.minecraft.entity.passive.EntityHorse.func_70612_e(EntityHorse.java:1279)
	at crazypants.enderzoo.entity.EntityFallenMount.func_70612_e(EntityFallenMount.java:203)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2078)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:144)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at net.minecraft.entity.passive.EntityHorse.func_70636_d(EntityHorse.java:980)
	at crazypants.enderzoo.entity.EntityFallenMount.func_70636_d(EntityFallenMount.java:164)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1869)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:1015)
	at crazypants.enderzoo.entity.EntityFallenMount.func_70071_h_(EntityFallenMount.java:146)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:906)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1746)
	at net.minecraft.entity.passive.EntityHorse.func_70612_e(EntityHorse.java:1279)
	at crazypants.enderzoo.entity.EntityFallenMount.func_70612_e(EntityFallenMount.java:203)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2078)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:144)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at net.minecraft.entity.passive.EntityHorse.func_70636_d(EntityHorse.java:980)
	at crazypants.enderzoo.entity.EntityFallenMount.func_70636_d(EntityFallenMount.java:164)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1869)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:1015)
	at crazypants.enderzoo.entity.EntityFallenMount.func_70071_h_(EntityFallenMount.java:146)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)

-- Entity being ticked --
Details:
	Entity Type: enderzoo.FallenMount (crazypants.enderzoo.entity.EntityFallenMount)
	Entity ID: 46354
	Entity Name: Zombie Horse
	Entity's Exact location: 1177.38, 64.01, -248.70
	Entity's Block location: World: (1177,64,-249), Chunk: (at 9,4,7 in 73,-16; contains blocks 1168,0,-256 to 1183,255,-241), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Entity's Momentum: 0.11, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
```

**Comment by CrazyPants** [comment]
This should be fixed in th elatest version. PLease re-raise if it isnt.
